name: CI
on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Redirect1
      run: echo "$PWD" 
    - name: Redirect2
      run: cd program
    - name: Redirect3
      run: echo "$PWD" 
    - name: Build
      run: dotnet build 